language: node_js
node_js:
    - "8.9.4"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install -g polymer-cli
after_success:
    - firebase deploy --token $FIREBASE_TOKEN
    